# Generated by Django 4.2.2 on 2023-06-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='avg_califications',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='num_califications',
            field=models.IntegerField(default=0),
        ),
    ]
